name: ucust-app

networks:
  ucust-net:
    external: true

services:
  api-gateway:
    image: ghcr.io/n4d3sh1k4-ucust-developing/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8100:8100"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx256m -Xms128m
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
    networks:
      - ucust-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 384M

  security-service:
    image: ghcr.io/n4d3sh1k4-ucust-developing/security-service:latest
    container_name: security-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx384m -Xms256m
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - VK_CLIENT_ID=${VK_CLIENT_ID}
      - VK_CLIENT_SECRET=${VK_CLIENT_SECRET}
    networks:
      - ucust-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M

  user-service:
    image: ghcr.io/n4d3sh1k4-ucust-developing/user-service:latest
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_TAILSCALE_IP=${SERVER_TAILSCALE_IP}
    networks:
      - ucust-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  business-service:
    image: ghcr.io/n4d3sh1k4-ucust-developing/business-service:latest
    container_name: business-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_TAILSCALE_IP=${SERVER_TAILSCALE_IP}
    networks:
      - ucust-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  notification-service:
    image: ghcr.io/n4d3sh1k4-ucust-developing/notification-service:latest
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - ucust-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 412M
