name: Full Stack Deployment

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Перечисли все свои сервисы здесь
        service: [api-gateway, security-service, user-service, business-service, netflix-eureka, notification-service]
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Скачивает код всех сервисов и common

      - name: Lowercase Registry Owner
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: . # Контекст — корень, чтобы Docker видел папку common
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Tailscale Connect
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Copy infrastructure files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app
            # Логинимся, чтобы Docker мог стянуть приватные образы
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
          
      - name: SSH and Update Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
